/**
 * RFC 9457: Problem Details for HTTP APIs
 * https://datatracker.ietf.org/doc/html/rfc9457
 */

/**
 * Base Problem Details interface according to RFC 9457
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type.
   * When dereferenced, it should provide human-readable documentation.
   * Default: "about:blank"
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type.
   * Should not change from occurrence to occurrence of the problem.
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server.
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem.
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem.
   * Optional field.
   */
  instance?: string;

  /**
   * Extension members: Additional members can be added to carry
   * problem-specific information.
   */
  [key: string]: unknown;
}

/**
 * Validation error detail for individual field errors
 */
export interface ValidationErrorDetail {
  /**
   * The field path that failed validation
   */
  field: string;

  /**
   * Human-readable error message
   */
  message: string;
}

/**
 * Problem Details for validation errors
 * Extends the base ProblemDetails with a validation-specific errors array
 */
export interface ValidationProblemDetails extends ProblemDetails {
  /**
   * Array of validation errors with details about each field that failed
   */
  errors: ValidationErrorDetail[];
}

/**
 * Constants for problem types
 */
export const ProblemTypes = {
  VALIDATION_ERROR: "/problems/validation-error",
  NOT_FOUND: "/problems/not-found",
  CONFLICT: "/problems/conflict",
  FORBIDDEN: "/problems/forbidden",
  UNAUTHORIZED: "/problems/unauthorized",
  INTERNAL_SERVER_ERROR: "/problems/internal-server-error",
  BAD_REQUEST: "/problems/bad-request",
} as const;
